import Image from "next/image";

type Props = { data: Record<string, unknown>; refId: number };

export default function ItineraryAIDocument({ data, refId }: Props) {
  const overview = (data.trip_overview ?? {}) as Record<string, string>;
  const flags = (data.routing_flags ?? []) as Array<{ type: string; title: string; detail: string }>;
  const routing = (data.routing_logic ?? {}) as { summary?: string; legs?: Array<{ from: string; to: string; mode: string; note?: string }> };
  const hotels = (data.hotels ?? []) as Array<{ city: string; nights: number; name: string; category: string; why: string; strengths: string[]; gen_ev_score: number; gen_ev_label: string }>;
  const restaurants = (data.restaurants ?? []) as Array<{ name: string; why: string; context: string; gen_ev_score: number }>;
  const days = (data.days ?? []) as Array<{ day: number; title: string; summary: string; activities: Array<{ time: string; place: string; description: string; duration: string; walking: string; senior_note?: string }>; meals: { breakfast?: string; lunch?: string; dinner?: string }; accommodation: string; gen_ev_score: number; gen_ev_label: string; day_type: string }>;
  const weather = (data.weather ?? []) as Array<{ location: string; conditions: string; packing_note: string }>;
  const rejected = (data.rejected_options ?? []) as Array<{ option: string; reason: string; constraint: string }>;
  const genEv = (data.overall_gen_ev ?? {}) as { score?: number; comfort?: number; accessibility?: number; safety?: number; label?: string; summary?: string };
  const dayScores = (data.day_scores ?? []) as Array<{ day: number; title: string; note: string; score: number; type: string; label: string }>;

  const PRI = "#821A52";

  return (
    <>
      <article className="itin-report mx-auto my-6 max-w-[820px] bg-white text-gray-900 shadow-md print:my-0 print:shadow-none">
        {/* Header */}
        <div className="px-8 pt-6 pb-5 text-white" style={{ background: PRI }}>
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-center gap-3">
              <Image src="/assets/marzi_crop.png" alt="Marzi" width={120} height={40} className="h-8 w-auto brightness-0 invert" priority />
              <span className="text-[9px] uppercase tracking-widest opacity-70">Travel Mitr</span>
            </div>
            <div className="text-right text-[9px] opacity-70">
              <div>Ref: MRZ-{refId.toString().padStart(6, "0")}</div>
              <div>Generated by Marzi AI</div>
            </div>
          </div>
          <h1 className="mt-4 text-xl font-bold">{overview.destination || "Trip Itinerary"}</h1>
          <p className="text-[12px] opacity-85 mt-0.5">{overview.duration} · {overview.travel_dates}</p>
          <p className="text-[12px] opacity-85">{overview.traveller_profile}</p>
        </div>

        <div className="px-8 py-5 space-y-5 text-[11.5px] leading-relaxed">

          {/* Score */}
          {genEv.score && (
            <div className="flex items-center gap-4 p-3 rounded border" style={{ borderColor: PRI, background: "#fdf2f8" }}>
              <div className="text-center">
                <div className="text-2xl font-bold" style={{ color: PRI }}>{genEv.score}</div>
                <div className="text-[9px] text-gray-500">/ 100</div>
              </div>
              <div className="flex-1">
                <div className="text-[12px] font-bold" style={{ color: PRI }}>{genEv.label || "SENIOR-FRIENDLY"}</div>
                <div className="text-[10px] text-gray-600 mt-0.5">
                  {genEv.comfort && `Comfort ${genEv.comfort}`} {genEv.accessibility && `· Accessibility ${genEv.accessibility}`} {genEv.safety && `· Safety ${genEv.safety}`}
                </div>
                {genEv.summary && <p className="text-[11px] text-gray-700 mt-1">{genEv.summary}</p>}
              </div>
            </div>
          )}

          {/* Overview */}
          <Sec title="Trip Overview" pri={PRI}>
            <div className="grid grid-cols-2 gap-x-4 gap-y-0.5 text-[11px]">
              {Object.entries(overview).map(([k, v]) => v && (
                <div key={k} className="flex gap-2">
                  <span className="min-w-[100px] text-gray-400 capitalize">{k.replace(/_/g, " ")}</span>
                  <span className="font-medium">{String(v).replace(/_/g, " ")}</span>
                </div>
              ))}
            </div>
          </Sec>

          {/* Routing Flags */}
          {flags.length > 0 && (
            <Sec title="Routing Flags" pri={PRI}>
              <div className="space-y-2">
                {flags.map((f, i) => {
                  const bg = f.type === "CRITICAL" ? "#fef2f2" : f.type === "ADVISORY" ? "#fffbeb" : "#f9fafb";
                  const bc = f.type === "CRITICAL" ? "#fca5a5" : f.type === "ADVISORY" ? "#fcd34d" : "#e5e7eb";
                  const tc = f.type === "CRITICAL" ? "#991b1b" : f.type === "ADVISORY" ? "#92400e" : "#374151";
                  return (
                    <div key={i} className="rounded p-2.5 text-[11px]" style={{ background: bg, border: `1px solid ${bc}` }}>
                      <span className="text-[9px] font-bold uppercase px-1.5 py-px rounded mr-2" style={{ background: bc, color: tc }}>{f.type}</span>
                      <strong>{f.title}</strong>
                      <p className="mt-1 text-gray-700">{f.detail}</p>
                    </div>
                  );
                })}
              </div>
            </Sec>
          )}

          {/* Routing legs */}
          {routing.legs && routing.legs.length > 0 && (
            <Sec title="Routing Logic" pri={PRI}>
              {routing.summary && <p className="text-[11px] text-gray-700 mb-2">{routing.summary}</p>}
              {routing.legs.map((l, i) => (
                <div key={i} className="text-[11px] mb-0.5"><strong>{l.from} → {l.to}</strong> — {l.mode} {l.note && <span className="text-gray-500 italic">({l.note})</span>}</div>
              ))}
            </Sec>
          )}

          {/* Hotels */}
          {hotels.length > 0 && (
            <Sec title="Recommended Stay" pri={PRI}>
              {hotels.map((h, i) => (
                <div key={i} className="mb-3 p-2.5 rounded border border-gray-200" style={{ pageBreakInside: "avoid" }}>
                  <div className="flex justify-between items-start">
                    <div><strong className="text-[12px]">{h.name}</strong><br /><span className="text-[10px] text-gray-500">{h.category} · {h.city} — {h.nights}N</span></div>
                    <span className="text-[11px] font-bold" style={{ color: PRI }}>{h.gen_ev_score}/100</span>
                  </div>
                  <p className="text-[11px] text-gray-700 mt-1">{h.why}</p>
                  {h.strengths?.length > 0 && <p className="text-[10px] text-gray-500 mt-1"><strong>Strengths:</strong> {h.strengths.join(" · ")}</p>}
                </div>
              ))}
            </Sec>
          )}

          {/* Restaurants */}
          {restaurants.length > 0 && (
            <Sec title="Recommended Dining" pri={PRI}>
              {restaurants.map((r, i) => (
                <div key={i} className="flex justify-between items-start border-b border-gray-100 pb-1.5 mb-1.5 last:border-0 text-[11px]">
                  <div><strong>{r.name}</strong> — {r.why} {r.context && <span className="text-gray-500 italic">({r.context})</span>}</div>
                  <span className="font-bold shrink-0 ml-2" style={{ color: PRI }}>{r.gen_ev_score}</span>
                </div>
              ))}
            </Sec>
          )}

          {/* Days */}
          {days.length > 0 && (
            <Sec title="Day-by-Day Itinerary" pri={PRI}>
              <div className="space-y-3">
                {days.map((d) => (
                  <div key={d.day} className="rounded border border-gray-200 overflow-hidden" style={{ pageBreakInside: "avoid" }}>
                    <div className="flex items-center justify-between px-3 py-2" style={{ background: "#f3f4f6" }}>
                      <div className="flex items-center gap-2">
                        <span className="flex h-6 w-6 items-center justify-center rounded-full text-white text-[10px] font-bold" style={{ background: PRI }}>{d.day}</span>
                        <span className="text-[12px] font-bold">{d.title}</span>
                        <span className="text-[9px] text-gray-500 uppercase">{d.day_type}</span>
                      </div>
                      <span className="text-[11px] font-bold" style={{ color: PRI }}>{d.gen_ev_score}/100</span>
                    </div>
                    <div className="px-3 py-2 space-y-1.5 text-[11px]">
                      {d.summary && <p className="text-gray-600 italic text-[10px]">{d.summary}</p>}
                      {d.activities.map((a, ai) => (
                        <div key={ai} className="flex gap-2">
                          <span className="font-semibold min-w-[50px] shrink-0" style={{ color: PRI }}>{a.time}</span>
                          <div>
                            <strong>{a.place}</strong>{a.duration && <span className="text-gray-500"> · {a.duration}</span>}
                            <p className="text-gray-600 text-[10.5px]">{a.description}</p>
                            {a.senior_note && <p className="text-[10px] text-amber-700 italic">{a.senior_note}</p>}
                          </div>
                        </div>
                      ))}
                      <div className="flex flex-wrap gap-x-3 text-[10px] text-gray-500 border-t border-gray-100 pt-1.5 mt-1">
                        {d.meals.breakfast && <span><strong>B:</strong> {d.meals.breakfast}</span>}
                        {d.meals.lunch && <span><strong>L:</strong> {d.meals.lunch}</span>}
                        {d.meals.dinner && <span><strong>D:</strong> {d.meals.dinner}</span>}
                        {d.accommodation && <span><strong>Stay:</strong> {d.accommodation}</span>}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Sec>
          )}

          {/* Weather */}
          {weather.length > 0 && (
            <Sec title="Weather & Packing" pri={PRI}>
              {weather.map((w, i) => (
                <p key={i} className="text-[11px] mb-0.5"><strong>{w.location}:</strong> {w.conditions}. <span className="italic text-gray-500">{w.packing_note}</span></p>
              ))}
            </Sec>
          )}

          {/* Rejected */}
          {rejected.length > 0 && (
            <Sec title="Rejected Options" pri={PRI}>
              {rejected.map((r, i) => (
                <div key={i} className="text-[11px] mb-1"><strong>{r.option}</strong> — {r.reason} <span className="text-red-600 italic text-[10px]">({r.constraint})</span></div>
              ))}
            </Sec>
          )}

          {/* Day Scores */}
          {dayScores.length > 0 && (
            <Sec title="Day-Level Scores" pri={PRI}>
              {dayScores.map((ds) => (
                <div key={ds.day} className="flex items-center gap-2 text-[11px] mb-0.5">
                  <span className="font-bold w-10" style={{ color: PRI }}>Day {ds.day}</span>
                  <span className="font-semibold min-w-[140px]">{ds.title}</span>
                  <span className="text-gray-500 flex-1">{ds.note}</span>
                  <span className="font-bold" style={{ color: PRI }}>{ds.score}/100</span>
                </div>
              ))}
            </Sec>
          )}
        </div>

        {/* Footer — on screen */}
        <div className="itin-footer-screen px-8 py-4" style={{ background: PRI, color: "white", borderTop: "2px solid #6b1545" }}>
          <div className="flex justify-between items-start text-[10px]">
            <div>
              <div className="text-[12px] font-bold">MARZI TRAVEL MITR</div>
              <div style={{ opacity: 0.75 }}>Senior-First Journeys for Generation Evergreen</div>
              <div style={{ opacity: 0.9 }}>Travel Assistance Desk — Darshan: 8792237778</div>
            </div>
            <div className="text-right">
              <div style={{ opacity: 0.5 }}>Generated by Marzi AI</div>
              <div className="text-[11px] font-bold mt-1">www.marzi.life</div>
            </div>
          </div>
        </div>
      </article>

      {/* Footer — repeated on every printed page */}
      <div className="itin-footer-print" style={{ background: PRI, color: "white" }}>
        <div className="flex justify-between items-start text-[10px] px-8 py-3">
          <div>
            <div className="text-[11px] font-bold">MARZI TRAVEL MITR</div>
            <div style={{ opacity: 0.8 }}>Travel Assistance Desk — Darshan: 8792237778 · www.marzi.life</div>
          </div>
          <div className="text-[9px] text-right" style={{ opacity: 0.5 }}>Generated by Marzi AI</div>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        .itin-report { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
        .itin-footer-print { display: none; }
        @media print {
          @page { size: A4; margin: 0; }
          body { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
          html, body { background: #fff !important; }
          .no-print { display: none !important; }
          .itin-report { box-shadow: none !important; margin: 0 !important; max-width: 100% !important; padding: 12mm 12mm 60px 12mm !important; }
          .itin-footer-screen { display: none !important; }
          .itin-footer-print {
            display: block !important;
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }
        }
      ` }} />
    </>
  );
}

function Sec({ title, pri, children }: { title: string; pri: string; children: React.ReactNode }) {
  return (
    <section style={{ pageBreakInside: "avoid" }}>
      <h2 className="text-[12px] font-bold mb-2 pb-1" style={{ borderBottom: `2px solid ${pri}`, color: pri }}>{title}</h2>
      {children}
    </section>
  );
}
