import Image from "next/image";

type Props = { data: Record<string, unknown>; refId: number };

export default function ItineraryAIDocument({ data, refId }: Props) {
  const overview = (data.trip_overview ?? {}) as Record<string, string>;
  const flags = (data.routing_flags ?? []) as Array<{ type: string; title: string; detail: string }>;
  const routing = (data.routing_logic ?? {}) as { summary?: string; legs?: Array<{ from: string; to: string; mode: string; note?: string }> };
  const hotels = (data.hotels ?? []) as Array<{ city: string; nights: number; name: string; category: string; why: string; strengths: string[]; gen_ev_score: number; gen_ev_label: string }>;
  const restaurants = (data.restaurants ?? []) as Array<{ name: string; why: string; context: string; gen_ev_score: number }>;
  const days = (data.days ?? []) as Array<{ day: number; title: string; summary: string; activities: Array<{ time: string; place: string; description: string; duration: string; walking: string; senior_note?: string }>; meals: { breakfast?: string; lunch?: string; dinner?: string }; accommodation: string; gen_ev_score: number; gen_ev_label: string; day_type: string }>;
  const weather = (data.weather ?? []) as Array<{ location: string; conditions: string; packing_note: string }>;
  const rejected = (data.rejected_options ?? []) as Array<{ option: string; reason: string; constraint: string }>;
  const genEv = (data.overall_gen_ev ?? {}) as { score?: number; comfort?: number; accessibility?: number; safety?: number; label?: string; summary?: string };
  const dayScores = (data.day_scores ?? []) as Array<{ day: number; title: string; note: string; score: number; type: string; label: string }>;

  return (
    <>
      <article className="itinerary-ai-doc mx-auto my-6 max-w-[820px] bg-white text-gray-900 shadow-md print:my-0 print:shadow-none">
        {/* Header */}
        <div className="bg-gradient-to-br from-primary/95 to-primary text-white px-10 pt-10 pb-8">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-center gap-3">
              <Image src="/assets/marzi_crop.png" alt="Marzi" width={140} height={46} className="h-9 w-auto brightness-0 invert" priority />
              <div className="text-[10px] uppercase tracking-widest opacity-80">Travel Mitr</div>
            </div>
            <div className="text-right text-[10px] opacity-80">
              <div>Ref: MRZ-{refId.toString().padStart(6, "0")}</div>
              <div>Generated by Marzi AI</div>
            </div>
          </div>
          <h1 className="mt-6 text-2xl sm:text-3xl font-bold">{overview.destination || "Trip Itinerary"}</h1>
          <p className="mt-1 text-sm opacity-90">{overview.duration} · {overview.travel_dates}</p>
          <p className="mt-1 text-sm opacity-90">{overview.traveller_profile}</p>
        </div>

        <div className="px-10 py-6 space-y-6 text-[13px] leading-relaxed">
          {/* Overall Score */}
          {genEv.score && (
            <div className="flex items-center gap-4 rounded-xl border-2 border-primary/30 bg-primary/5 p-4">
              <div className="text-center">
                <div className="text-3xl font-bold text-primary">{genEv.score}</div>
                <div className="text-[10px] text-gray-500">/ 100</div>
              </div>
              <div className="flex-1">
                <div className="text-sm font-bold text-primary">{genEv.label || "SENIOR-FRIENDLY"}</div>
                <div className="flex gap-4 mt-1 text-[11px] text-gray-600">
                  {genEv.comfort && <span>Comfort {genEv.comfort}</span>}
                  {genEv.accessibility && <span>· Accessibility {genEv.accessibility}</span>}
                  {genEv.safety && <span>· Safety {genEv.safety}</span>}
                </div>
                {genEv.summary && <p className="mt-1 text-[12px] text-gray-700">{genEv.summary}</p>}
              </div>
            </div>
          )}

          {/* Trip Overview */}
          <Section title="Trip Overview">
            <div className="grid grid-cols-2 gap-x-6 gap-y-1 text-[12.5px]">
              {Object.entries(overview).map(([k, v]) => v && (
                <div key={k} className="flex gap-2">
                  <span className="min-w-[120px] text-gray-500 capitalize">{k.replace(/_/g, " ")}</span>
                  <span className="font-medium">{v}</span>
                </div>
              ))}
            </div>
          </Section>

          {/* Routing Flags */}
          {flags.length > 0 && (
            <Section title="Routing Flags">
              <div className="space-y-3">
                {flags.map((f, i) => (
                  <div key={i} className={`rounded-lg border p-3 ${f.type === "CRITICAL" ? "border-red-300 bg-red-50" : f.type === "ADVISORY" ? "border-amber-300 bg-amber-50" : "border-gray-200 bg-gray-50"}`}>
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded ${f.type === "CRITICAL" ? "bg-red-200 text-red-800" : f.type === "ADVISORY" ? "bg-amber-200 text-amber-800" : "bg-gray-200 text-gray-700"}`}>{f.type}</span>
                      <span className="text-sm font-semibold">{f.title}</span>
                    </div>
                    <p className="text-[12px] text-gray-700">{f.detail}</p>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Routing Logic */}
          {routing.legs && routing.legs.length > 0 && (
            <Section title="Routing Logic & City Distribution">
              {routing.summary && <p className="text-[12px] text-gray-700 mb-3">{routing.summary}</p>}
              <div className="space-y-1">
                {routing.legs.map((leg, i) => (
                  <div key={i} className="flex items-center gap-2 text-[12px]">
                    <span className="font-semibold min-w-[120px]">{leg.from} → {leg.to}</span>
                    <span className="text-gray-600">{leg.mode}</span>
                    {leg.note && <span className="text-gray-500 italic">({leg.note})</span>}
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Hotels */}
          {hotels.length > 0 && (
            <Section title="Recommended Stay Options">
              <div className="space-y-4">
                {hotels.map((h, i) => (
                  <div key={i} className="rounded-lg border border-gray-200 p-4 print:break-inside-avoid">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="font-bold text-sm">{h.name}</div>
                        <div className="text-[11px] text-gray-500">{h.category} · {h.city} — {h.nights} Night{h.nights > 1 ? "s" : ""}</div>
                      </div>
                      <ScoreBadge score={h.gen_ev_score} label={h.gen_ev_label} />
                    </div>
                    <p className="mt-2 text-[12px] text-gray-700">{h.why}</p>
                    {h.strengths?.length > 0 && (
                      <div className="mt-2 text-[11px] text-gray-600">
                        <strong>Strengths:</strong> {h.strengths.join(" · ")}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Restaurants */}
          {restaurants.length > 0 && (
            <Section title="Recommended Dining">
              <div className="space-y-2">
                {restaurants.map((r, i) => (
                  <div key={i} className="flex items-start justify-between gap-3 border-b border-gray-100 pb-2 last:border-0">
                    <div>
                      <div className="font-semibold text-[12.5px]">{r.name}</div>
                      <div className="text-[11px] text-gray-600">{r.why}</div>
                      {r.context && <div className="text-[10px] text-gray-500 italic">{r.context}</div>}
                    </div>
                    <span className="shrink-0 text-[11px] font-bold text-primary">{r.gen_ev_score}/100</span>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Day-by-Day */}
          {days.length > 0 && (
            <Section title="Day-by-Day Itinerary">
              <div className="space-y-5">
                {days.map((d) => (
                  <div key={d.day} className="border border-gray-200 rounded-xl overflow-hidden print:break-inside-avoid">
                    <div className="flex items-center justify-between bg-gray-50 px-4 py-2.5 border-b border-gray-200">
                      <div className="flex items-center gap-2">
                        <span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-white text-xs font-bold">{d.day}</span>
                        <div>
                          <span className="text-sm font-bold">{d.title}</span>
                          <span className="ml-2 text-[10px] text-gray-500 uppercase">{d.day_type}</span>
                        </div>
                      </div>
                      <ScoreBadge score={d.gen_ev_score} label={d.gen_ev_label} small />
                    </div>
                    <div className="p-4 space-y-3">
                      {d.summary && <p className="text-[12px] text-gray-600 italic">{d.summary}</p>}
                      {d.activities.map((a, ai) => (
                        <div key={ai} className="flex gap-3">
                          <span className="text-[11px] font-semibold text-primary min-w-[60px] shrink-0">{a.time}</span>
                          <div>
                            <div className="text-[12.5px] font-semibold">{a.place}</div>
                            <p className="text-[12px] text-gray-600">{a.description}</p>
                            <div className="flex flex-wrap gap-x-3 mt-0.5 text-[10px] text-gray-500">
                              {a.duration && <span>{a.duration}</span>}
                              {a.walking && <span>Walking: {a.walking}</span>}
                              {a.senior_note && <span className="text-amber-600">{a.senior_note}</span>}
                            </div>
                          </div>
                        </div>
                      ))}
                      <div className="flex flex-wrap gap-x-4 text-[11px] text-gray-600 border-t border-gray-100 pt-2 mt-2">
                        {d.meals.breakfast && <span><strong>B:</strong> {d.meals.breakfast}</span>}
                        {d.meals.lunch && <span><strong>L:</strong> {d.meals.lunch}</span>}
                        {d.meals.dinner && <span><strong>D:</strong> {d.meals.dinner}</span>}
                        {d.accommodation && <span><strong>Stay:</strong> {d.accommodation}</span>}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Weather */}
          {weather.length > 0 && (
            <Section title="Weather & Packing">
              <div className="space-y-1">
                {weather.map((w, i) => (
                  <div key={i} className="text-[12px]">
                    <strong>{w.location}:</strong> {w.conditions}. <span className="text-gray-500 italic">{w.packing_note}</span>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Rejected Options */}
          {rejected.length > 0 && (
            <Section title="Rejected Options">
              <div className="space-y-1 text-[12px]">
                {rejected.map((r, i) => (
                  <div key={i} className="flex gap-2">
                    <span className="font-semibold min-w-[160px] text-gray-700">{r.option}</span>
                    <span className="text-gray-600">{r.reason}</span>
                    <span className="text-[10px] text-red-500 italic shrink-0">({r.constraint})</span>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Day Scores */}
          {dayScores.length > 0 && (
            <Section title="Day-Level Scores">
              <div className="space-y-1">
                {dayScores.map((ds) => (
                  <div key={ds.day} className="flex items-center gap-3 text-[12px]">
                    <span className="font-bold text-primary w-10">Day {ds.day}</span>
                    <span className="font-semibold min-w-[160px]">{ds.title}</span>
                    <span className="text-gray-500 flex-1">{ds.note}</span>
                    <span className="font-bold text-primary">{ds.score}/100</span>
                    <span className="text-[10px] text-gray-500">{ds.label}</span>
                  </div>
                ))}
              </div>
            </Section>
          )}
        </div>

        {/* Footer */}
        <footer className="border-t-2 border-primary/60 px-10 py-4 flex flex-wrap items-center justify-between gap-2 text-[11px] text-gray-600">
          <div>
            <span className="font-semibold text-primary">Marzi Travel Mitr</span> · Senior-First Journeys for Generation Evergreen
          </div>
          <div>Darshan: 8792237778 · www.marzi.life</div>
        </footer>
      </article>

      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          @page { size: A4; margin: 10mm; }
          html, body { background: #fff !important; }
          .no-print { display: none !important; }
          .itinerary-ai-doc { box-shadow: none !important; margin: 0 !important; max-width: 100% !important; }
          .itinerary-ai-doc section { break-inside: avoid; page-break-inside: avoid; }
          .print\\:break-inside-avoid { break-inside: avoid; page-break-inside: avoid; }
        }
      ` }} />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-[11px] font-semibold uppercase tracking-wider text-primary mb-2 border-b border-primary/20 pb-1">{title}</h2>
      {children}
    </section>
  );
}

function ScoreBadge({ score, label, small }: { score: number; label: string; small?: boolean }) {
  return (
    <div className={`text-center shrink-0 ${small ? "" : ""}`}>
      <div className={`font-bold text-primary ${small ? "text-sm" : "text-base"}`}>{score}<span className="text-[10px] text-gray-400">/100</span></div>
      <div className="text-[9px] text-gray-500 uppercase">{label}</div>
    </div>
  );
}
